version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    environment:
      - PYTHONPATH=/app
    command: python src/realtime/web_app.py
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  verifier:
    build: .
    volumes:
      - ./:/app/
    environment:
      - PYTHONPATH=/app
    command: python src/realtime/verifier.py
    restart: unless-stopped
    depends_on:
      - web